### ISSUE TITLE
Processed orders get Cancelled while money has been taken from customers account

### ISSUE THREAD

**Issue by anziv** [DIBS-Payment-Services/Magento-D2-FlexWin#1]
Hi,

We installed module Dibsfw-3.2.0 on Magento version 1.9.1.0 and activated it this June. We get a lot of orders that we can't invoice next day because we don't see the button to Invoice. 
Such orders get status Cancelled for all products in the order and in magento comments we see text below. It seems like while customer fill in their cards data the order is cancelled, but it is not affecting payment. Please, check.
22 aug 2016 17:51:20|Väntar på granskning
Kund Notification Not Applicable 
Kunden har kommit tillbaka till butiken från DIBS Payment Services (www.dibs.se)
**22 aug 2016 17:50:05|Avbruten**
Kund Notification Not Applicable
22 aug 2016 17:47:18|Inväntar betalning
Kund Inte meddelad 
Ordern har blivit mottagen och betalningen bearbetas av DIBS betalningssystem (www.dibs.se)
22 aug 2016 17:47:16|Inväntar betalning
Kund Meddelad

**Comment by maxwhite** [comment]
Hi, have you filled in Magento admin these fields:
DIBS API login
DIBS API password
?

**Comment by anziv** [comment]
Hi,
Yes, we did this like you mentioned, dibs api login and dibs api pass.

Skickat från Yahoo Mail på Android 
 
  Den tis, aug 2016 klockan 12:04, maxwhite<notifications@github.com> skrev:   
Hi, have you filled in Magento admin these fields:
DIBS API login
DIBS API password
?

**Comment by anziv** [comment]
Hi, 

Should we remove the data from DIBS API login and DIBS API password in magento backend if it cause the problem?

**Comment by maxwhite** [comment]
Hi, could you please write to me to this email.
mabe@dibs.dk
Please provide your merchant id in the email

**Comment by anziv** [comment]
Hi,

I sent you mail! Please check.
